const CGI_PROTOCOL = 'http';
const CGI_HOST = '122.13.25.44';
const CGI_PORT = 9902;
const CGI_BASE_URL = `${CGI_PROTOCOL}://${CGI_HOST}:${CGI_PORT}`;
const CGI_DEFAULT_REQUEST_TIMEOUT = 30000;
export {
    CGI_BASE_URL,
    CGI_DEFAULT_REQUEST_TIMEOUT
};